import Hawk.CyclotomicSigning
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Ring

/-! Concrete deterministic bridges from the HAWK specification. -/
noncomputable section
set_option autoImplicit false
open scoped BigOperators Matrix
open Matrix

namespace Hawk.Concrete

open Hawk.CyclotomicTrace
open Hawk.CyclotomicSigning

variable {E : Type*} [Field E] [Algebra ℚ E]

/-- The concrete coefficient ring generated by the canonical HAWK root of unity: `ℤ[ζ]`. -/
def coeffRing (k : ℕ) [IsCyclotomicExtension {hawkConductor k} ℚ E] : Subring E :=
  Subring.closure {hawkZeta (E := E) k}

/-- The canonical root of unity belongs to `ℤ[ζ]`. -/
theorem hawkZeta_mem_coeffRing (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E] :
    hawkZeta (E := E) k ∈ coeffRing (E := E) k := by
  exact Subring.subset_closure (Set.mem_singleton _)

section KeyBasis

variable {R : Type*} [CommRing R]

/-- The rank-two NTRU basis appearing in HAWK key generation. -/
def keyMatrix (f F g G : R) : Matrix (Fin 2) (Fin 2) R :=
  !![f, F; g, G]

/-- The adjugate candidate for a determinant-one HAWK basis. -/
def keyMatrixInv (f F g G : R) : Matrix (Fin 2) (Fin 2) R :=
  !![G, -F; -g, f]

/-- The NTRU relation `fG - gF = 1` constructs an actual element of `GL₂(R)`. -/
def keyBasis (f F g G : R) (hdet : f * G - g * F = 1) :
    (Matrix (Fin 2) (Fin 2) R)ˣ where
  val := keyMatrix f F g G
  inv := keyMatrixInv f F g G
  val_inv := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [keyMatrix, keyMatrixInv, Matrix.mul_apply, Fin.sum_univ_two] <;>
      ring_nf at hdet ⊢ <;> assumption
  inv_val := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [keyMatrix, keyMatrixInv, Matrix.mul_apply, Fin.sum_univ_two] <;>
      ring_nf at hdet ⊢ <;> assumption

@[simp] theorem keyBasis_val (f F g G : R) (hdet : f * G - g * F = 1) :
    (↑(keyBasis f F g G hdet) : Matrix (Fin 2) (Fin 2) R) = keyMatrix f F g G := rfl

@[simp] theorem keyBasis_inv_val (f F g G : R) (hdet : f * G - g * F = 1) :
    (↑((keyBasis f F g G hdet)⁻¹) : Matrix (Fin 2) (Fin 2) R) =
      keyMatrixInv f F g G := rfl

end KeyBasis

/-! ## Canonical coefficient extraction -/

/-- The HAWK power basis reindexed by the scheme degree `n = 2^k`. -/
def hawkBasis (k : ℕ) [IsCyclotomicExtension {hawkConductor k} ℚ E] :
    Basis (Fin (hawkDegree k)) ℚ E := by
  let pb := (hawkZeta_spec (E := E) k).powerBasis ℚ
  have hdim : pb.dim = hawkDegree k := by
    calc
      pb.dim = Module.finrank ℚ E := pb.finrank.symm
      _ = hawkDegree k := finrank_hawkCyclotomic (E := E) k
  exact pb.basis.reindex (Fin.castOrderIso hdim).toEquiv

/-- The reindexed power basis is literally `1, ζ, ..., ζ^(n-1)`. -/
theorem hawkBasis_apply (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (i : Fin (hawkDegree k)) :
    hawkBasis (E := E) k i = hawkZeta (E := E) k ^ (i : ℕ) := by
  let pb := (hawkZeta_spec (E := E) k).powerBasis ℚ
  have hdim : pb.dim = hawkDegree k := by
    calc
      pb.dim = Module.finrank ℚ E := pb.finrank.symm
      _ = hawkDegree k := finrank_hawkCyclotomic (E := E) k
  change (pb.basis.reindex (Fin.castOrderIso hdim).toEquiv) i =
    hawkZeta (E := E) k ^ (i : ℕ)
  rw [Basis.reindex_apply, PowerBasis.basis_eq_pow, IsPrimitiveRoot.powerBasis_gen]
  congr 1

/-- Canonical rational power-basis coordinates of a cyclotomic-field element. -/
def coeffs (k : ℕ) [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (x : E) : Fin (hawkDegree k) → ℚ :=
  (hawkBasis (E := E) k).equivFun x

/-- Re-expanding the canonical coordinates recovers the original element. -/
theorem coeffExpansion_coeffs (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E] (x : E) :
    coeffExpansion (hawkZeta (E := E) k) (coeffs (E := E) k x) = x := by
  unfold coeffExpansion coeffs
  rw [Basis.equivFun_apply]
  calc
    (∑ i, ((hawkBasis (E := E) k).repr x) i •
      (hawkZeta (E := E) k) ^ (i : ℕ)) =
        ∑ i, ((hawkBasis (E := E) k).repr x) i • hawkBasis (E := E) k i := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [hawkBasis_apply]
    _ = x := (hawkBasis (E := E) k).sum_repr x

/-- Coefficients of a whole module vector. -/
def vectorCoeffs {ι : Type*} (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (x : ι → E) : ι → Fin (hawkDegree k) → ℚ :=
  fun i => coeffs (E := E) k (x i)

/-- The old explicit `x = coeffVector a` obligation is discharged canonically. -/
theorem coeffVector_vectorCoeffs {ι : Type*} [Fintype ι] (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (x : ι → E) :
    coeffVector (E := E) k (vectorCoeffs (E := E) k x) = x := by
  funext i
  exact coeffExpansion_coeffs (E := E) k (x i)

/-- Coefficient extraction is linear under negation. -/
theorem coeffs_neg (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E] (x : E) :
    coeffs (E := E) k (-x) = -coeffs (E := E) k x := by
  funext i
  simp [coeffs, Basis.equivFun_apply]

/-! ## Explicit signing-coset point -/

variable [CharZero E]

/-- A point constructed from an explicit signing-coset witness in the form `Bh + 2z`. -/
def cosetPoint (R : Subring E) (B₀ : (Matrix (Fin 2) (Fin 2) R)ˣ)
    (h₀ z₀ : Fin 2 → R) : Fin 2 → E :=
  let B := Hawk.ambientBasis R B₀
  let h : Fin 2 → E := fun i => (h₀ i : E)
  let z : Fin 2 → E := fun i => (z₀ i : E)
  (↑B : Matrix (Fin 2) (Fin 2) E) *ᵥ h + (2 : E) • z

-- Every point constructed from an integral witness supplies `InSigningCoset` automatically.
omit [Algebra ℚ E] [CharZero E] in
theorem cosetPoint_in_coset (R : Subring E)
    (B₀ : (Matrix (Fin 2) (Fin 2) R)ˣ) (h₀ z₀ : Fin 2 → R) :
    Hawk.InSigningCoset R
      (↑(Hawk.ambientBasis R B₀) : Matrix (Fin 2) (Fin 2) E)
      (fun i => (h₀ i : E)) (cosetPoint R B₀ h₀ z₀) := by
  refine ⟨(fun i => (z₀ i : E)), ?_, ?_⟩
  · intro i
    exact (z₀ i).property
  · rfl

/-! ## Automatic coefficient-norm endpoint -/

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The cyclotomic coefficient-norm theorem with no externally supplied coefficient witness. -/
theorem signing_correctness_mod_coeff_norm_auto (m : ℕ) (hm : m ≠ 0) (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (R : Subring E) (B : (Matrix ι ι E)ˣ)
    (hBinv : Hawk.IntegralMat R (↑(B⁻¹) : Matrix ι ι E))
    (h x : ι → E)
    (hx : Hawk.InSigningCosetMod m R (↑B : Matrix ι ι E) h x) :
    let a := vectorCoeffs (E := E) k x
    let Q := cyclotomicGram (E := E) k (↑B : Matrix ι ι E)
    let w := Hawk.preimage B x
    let s := Hawk.signatureMod m B h x
    Hawk.IntegralVec R s ∧
      h - w = (m : E) • s ∧
      h - (m : E) • s = w ∧
      (↑B : Matrix ι ι E) *ᵥ w = x ∧
      cyclotomicPublicSq (E := E) k Q (h - (m : E) • s) = coeffSqR k a ∧
      cyclotomicPublicLength (E := E) k Q (h - (m : E) • s) = coeffLength k a := by
  dsimp only
  exact signing_correctness_mod_coeff_norm (E := E) m hm k R B hBinv h x hx
    (vectorCoeffs (E := E) k x) (coeffVector_vectorCoeffs (E := E) k x).symm

/--
HAWK-shaped rank-two algebraic interface. The coefficient ring is `ℤ[ζ]`, the
basis is constructed directly from `f,F,g,G` and the NTRU relation, the input
point is constructed from an explicit signing-coset witness, and rational
power-basis coordinates are extracted canonically rather than assumed. This
does not formalize the binary hash-output restriction or the probabilistic sampler.
-/
theorem hawk_rank2_algebraic_interface (k : ℕ)
    [IsCyclotomicExtension {hawkConductor k} ℚ E]
    (f F g G : coeffRing (E := E) k)
    (hdet : f * G - g * F = 1)
    (h₀ z₀ : Fin 2 → coeffRing (E := E) k) :
    let R := coeffRing (E := E) k
    let B₀ := keyBasis f F g G hdet
    let B := Hawk.ambientBasis R B₀
    let h : Fin 2 → E := fun i => (h₀ i : E)
    let x := cosetPoint R B₀ h₀ z₀
    let a := vectorCoeffs (E := E) k x
    let Q := cyclotomicGram (E := E) k (↑B : Matrix (Fin 2) (Fin 2) E)
    let w := Hawk.preimage B x
    let s := Hawk.signature B h x
    Hawk.IntegralVec R s ∧
      h - w = (2 : E) • s ∧
      h - (2 : E) • s = w ∧
      (↑B : Matrix (Fin 2) (Fin 2) E) *ᵥ w = x ∧
      cyclotomicPublicSq (E := E) k Q (h - (2 : E) • s) = coeffSqR k a ∧
      cyclotomicPublicLength (E := E) k Q (h - (2 : E) • s) = coeffLength k a := by
  dsimp only
  let R := coeffRing (E := E) k
  let B₀ := keyBasis f F g G hdet
  have hx := cosetPoint_in_coset (E := E) R B₀ h₀ z₀
  exact signing_correctness_mod_coeff_norm_auto (E := E) 2 (by decide) k R
    (Hawk.ambientBasis R B₀) (Hawk.ambientBasis_inv_integral R B₀)
    (fun i => (h₀ i : E)) (cosetPoint R B₀ h₀ z₀) hx

end Hawk.Concrete
